### ISSUE TITLE
是否可以支持换肤功能

### ISSUE THREAD

**Issue by yockii** [Teal/TealUI#30]
因为不同项目颜色风格可能不一样，如何快速更改主题颜色呢

**Comment by xuld** [comment]
整个项目是使用less的，大部分组件都使用了 src/core/mixins.less 提供的变量，只需修改这个文件然后重新生成项目的所有css，（比如批量修改背景色为黑色，修改整体色系变橙色）即可批量修改主体样式。对于特定组件，需要直接进入这个组件，修改其源码less或css，然后重新打包即可。
